core/urls.py
from django.urls import path

from .views import (HomeView, ItemDetailView, add_to_cart, remove_from_the_cart, OrderSummary,
                    remove_single_from_the_cart, CheckoutView, PaymentView, AddCouponView,
                    RequestRefundView, add_likes_to_product, CustomerProfileView, add_comment_to_item,
                    complete_payment
                    )

app_name = 'core'

urlpatterns = [
     path('',
          HomeView.as_view(), name='item_list'),
     path('item_list/<category_name>/',
          HomeView.as_view(), name='item_list_by_category'),
     path('checkout/',
          CheckoutView.as_view(), name='checkout'),
     path('payment/<payment_option>/',
          PaymentView.as_view(), name="payment"),
     path('products/<slug>/',
          ItemDetailView.as_view(), name='products'),
     path('order_summary/',
          OrderSummary.as_view(), name='order_summary'),
     path('customer_profile/',
          CustomerProfileView.as_view(), name='customer_profile'),
     path('add_to_cart/<slug>/',
          add_to_cart, name='add_to_cart'),
     path('remove_from_the_cart/<slug>/',
          remove_from_the_cart, name='remove_from_the_cart'),
     path('remove_single_from_the_cart/<slug>/',
          remove_single_from_the_cart, name='remove_single_from_the_cart'),
     path('add_coupon/',
          AddCouponView.as_view(), name="add_coupon"),
     path('request_refund/',
          RequestRefundView.as_view(), name="request_refund"),
     path('add_likes_to_product/<slug>/',
          add_likes_to_product, name="likes"),
     path('add_comment_to_item/<slug>/',
          add_comment_to_item, name="comments"),
     path('complete_payment/<tran_id>/<payment_type>/',
          complete_payment, name='complete_payment'),

]

djangoecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.shortcuts import reverse

from django_countries.fields import CountryField

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping')
)


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=20, blank=True, null=True)
    on_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    category = models.CharField(max_length=30)

    def __str__(self):
        return self.category

    def get_absolute_url(self):
        return reverse("core:item_list_by_category", kwargs={
            "category_name": self.category
        })


class Item(models.Model):
    item_name = models.CharField(max_length=100)
    item_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    item_image = models.ImageField(upload_to='items_images/')
    labels = models.CharField(choices=LABEL_CHOICES, max_length=2)
    slug = models.SlugField(unique=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    description = models.TextField()

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse('core:products', kwargs={
            'slug': self.slug
        })

    def get_add_to_cart(self):
        return reverse('core:add_to_cart', kwargs={
            'slug': self.slug
        })

    def remove_from_the_cart(self):
        return reverse('core:remove_from_the_cart', kwargs={
            'slug':self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.item_name}"

    def get_total_price(self):
        return self.item.price * self.quantity
    
    def get_total_discount_price(self):
        return self.item.discount_price * self.quantity

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_price()
        else:
            return self.get_total_price()


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    billing_address = models.ForeignKey('Address', related_name='billing_address',
                                        on_delete=models.SET_NULL, blank=True, null=True)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address',
                                         on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', models.SET_NULL, blank=True, null=True)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    reference_code = models.CharField(max_length=20)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total = total + order_item.get_final_price()
        if self.coupon is not None:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = models.CharField(max_length=200, choices=CountryField().choices + [('', 'Select Country')])
    zip_code = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    stripe_charge_id = models.CharField(max_length=50, null=True, blank=True)
    ssl_charge_id = models.CharField(max_length=50, null=True, blank=True)
    amount = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)


class Coupon(models.Model):
    coupon = models.CharField(max_length=30)
    amount = models.IntegerField()

    def __str__(self):
        return self.coupon


class Refund(models.Model):
    order = models.ForeignKey(Cart, on_delete=models.CASCADE)
    reference_code = models.CharField(max_length=20)
    reason = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return str(self.pk)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment


def user_profile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        user_profile = UserProfile.objects.create(user=instance)


# Signal to create user profile every time a new user is created
post_save.connect(user_profile_receiver, sender=settings.AUTH_USER_MODEL)

core/forms.py
from django import forms

from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

from .models import Comment

CHOICE_FIELDS = (
    ('S', 'Stripe'),
    ('P', 'Paypal'),
)


class CheckoutForm(forms.Form):
    # Shipping information
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    shipping_zip = forms.CharField(required=False)
    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)

    # Billing information
    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    billing_zip = forms.CharField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    # Payment Method
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICE_FIELDS)


class CouponForm(forms.Form):
    coupon_code = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control",
        'placeholder': 'Promo Code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby':"basic-addon2"
        }
    ))


class RefundForm(forms.Form):
    reference_code = forms.CharField(max_length=20)
    reason = forms.CharField(widget=forms.Textarea(attrs={
        "row": 2
    }))
    email = forms.EmailField()


class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea(attrs={
        "cols": 200,
        "rows": 3,
        "class": "form-control",
        "placeholder": "Write A Comment"
    }))

templates/any_form.html
<main>
    <div class="container">
      <section class="mb-4">
        <div class="row wow fadeIn">
          <div class='col-6 offset-3'>
              <form>
                   {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">
                      Submit
                  </button>
                </form>
          </div>
        </div>
      </section>
    </div>
 </main>

templates/base.html
<!DOCTYPE html>
<html lang="en">

    {% include 'head.html' %}
    {% include 'navbar.html' %}
    <body>
        <div class="mt-5 pt-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

        {% block content %}
        {% endblock %}

        {% block extra_body %}
        {% endblock %}

        {% include 'script.html' %}
        {% block extra_scripts %}
        {% endblock extra_scripts %}

    </body>
</html>

templates/category.html
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
              {% for cat in categories %}
            <li class="nav-item">
              <a class="nav-link" href="{{cat.get_absolute_url}}">{{cat.category}}</a>
            </li>
              {% endfor %}
          </ul>
          <!-- Links -->

          <form class="form-inline" method="get" action="/">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" name="key" placeholder="Search by name/category" aria-label="Search">
                <button type="submit">Search</button>
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>

templates/complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="5; url={% url 'core:item_list' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="mt-5 pt-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>
</body>
</html>

templates/customer_profile.html
{% extends 'base.html' %}
{% block content %}
<h2 class="h2 text-center">Order History</h2>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Order</th>
      <th scope="col">Date</th>
      <th scope="col">Items</th>
      <th scope="col">Total(BDT)</th>
      <th scope="col">Reference Code</th>
      <th scope="col">Request Refund</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        {% for order in orders %}
        <th><strong>{{forloop.counter}}</strong></th>
        <td><strong>{{order.ordered_date|date:'Y/m/d'}}</strong></td>
      <td>
          {% for item in order.items.all %}
          <li style="list-style-type:none;">
              <strong>{{item}}</strong>
          </li>
          {% endfor %}

      </td>
        <td><strong>{{order.payment.amount}}</strong></td>
        <td><strong>{{order.reference_code}}</strong></td>
        {% if order.refund_requested %}
        <td><b><strong style="color:red;">Refund Requested</strong></b></td>
        {% elif order.refund_granted %}
        <td><b><strong style="color:green;">Refund Granted</strong></b></td>
        {% else %}
        <td><a style="color:blue;" href="/request_refund/"><b><strong>Refund</strong></b></a></td>
        {% endif %}
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock content %}






<!--{% for order in orders %}-->
<!--<ul>-->
<!--    <li> {{forloop.counter}}-->
<!--        <p>-->
<!--            Reference Code {{order.reference_code}}-->
<!--        </p>-->
<!--        <ul>Ordered Items-->
<!--            {% for item in order.items.all %}-->
<!--            <li>-->
<!--                name : {{item.item.item_name}}-->
<!--            </li>-->
<!--            {% endfor %}-->
<!--        </ul>-->
<!--        {% if order.coupon %}-->
<!--        <p>-->
<!--            Coupon : {{order.coupon}}-->
<!--        </p>-->
<!--        {% endif %}-->
<!--        <p>-->
<!--            Total Amount {{order.payment.amount}}-->
<!--        </p>-->
<!--    </li>-->
<!--</ul>-->
<!--{% endfor %}-->

templates/footer.html
{% load static %}

<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank"
        role="button">Download MDB
        <i class="fas fa-download ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">Start
        free tutorial
        <i class="fas fa-graduation-cap ml-2"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/order_snippet.html
<div class="col-md-12 mb-4">
  <h4 class="d-flex justify-content-between align-items-center mb-3">
  <span class="text-muted">Your cart</span>
  <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
  </h4>
  <ul class="list-group mb-3 z-depth-1">
  {% for order_item in orders.items.all %}
  <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
      <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.item_name}}</h6>
      <small class="text-muted">{{ order_item.item.description|truncatewords:10}}</small>
      </div>
      <span class="text-muted">{{ order_item.get_final_price }}</span>
  </li>
  {% endfor %}
  {% if orders.coupon %}
  <li class="list-group-item d-flex justify-content-between bg-light">
      <div class="text-success">
      <h6 class="my-0">{{orders.coupon.coupon}}</h6>
      <small>{{ orders.coupon.code }}</small>
      </div>
      <span class="text-success">-{{ orders.coupon.amount }}</span>
  </li>
  {% endif %}
  <li class="list-group-item d-flex justify-content-between">
      <span>Total (BDT)</span>
      <strong>{{ orders.get_total }}</strong>
  </li>
  </ul>

  {% if DISPLAY_COUPON_FORM %}
  <form class="card p-2" action="{% url 'core:add_coupon' %}" method="POST">
      <p>Promo Code = Django</p>
      {% csrf_token %}
      <div class="input-group">
          {{ coupon_form.coupon_code }}
          <div class="input-group-append">
          <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
          </div>
      </div>
  </form>
  {% endif %}

</div>

templates/order_summary.html
<!DOCTYPE html>
<html lang="en">

    {% extends 'base.html' %}
    
    <body>

        {% block content %}
        <main>
            <div class="container">
                <div class="table-responsive text-nowrap">
                    <h2>Order Summary</h2>

                    <table class="table">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Item Title</th>
                          <th scope="col">Price</th>
                          <th scope="col">Quantity</th>
                          <th scope="col">Total Price</th>
                        </tr>
                      </thead>
                      <tbody>
                          {% for order_item in object.items.all %}
                        <tr>
                          <th scope="row">{{forloop.counter}}</th>
                          <td>{{order_item.item.item_name}}</td>
                          {% if order_item.item.discount_price %}
                          <td>
                            <a href="{% url 'core:remove_single_from_the_cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                            {{order_item.item.discount_price}}
                            <a href="{% url 'core:add_to_cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                          </td>
                          {% else %}
                          <td>
                              <a href="{% url 'core:remove_single_from_the_cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                            {{order_item.item.price}}
                            <a href="{% url 'core:add_to_cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                          </td>
                          {% endif %}
                          <td>{{order_item.quantity}}</td>
                          {% if order_item.item.discount_price %}
                          <td>
                            {{order_item.get_total_discount_price}}
                            <a style="color: red;" href="{% url 'core:remove_from_the_cart' order_item.item.slug %}"><i class="fas fa-trash float-right"></i></a>
                          </td>
                          {% else %}
                          <td>
                            {{order_item.get_total_price}}
                            <a style="color: red;" href="{% url 'core:remove_from_the_cart' order_item.item.slug %}"><i class="fas fa-trash float-right"></i></a>
                          </td>
                          {% endif %}
                        </tr>
                        {% empty %}
                        <tr>
                          <td colspan="5">Your car is empty</td>
                        </tr>
                        {% endfor %}
                          {% if object.coupon %}
                          <tr>
                          <td colspan="4"><b>Coupon</b></td>
                          <td>{{object.coupon.amount}}</td>
                        </tr>
                          {% endif %}
                        <tr>
                          <td colspan="4"><b>Order Total</b></td>
                          <td>{{object.get_total}}</td>
                        </tr>
                        <tr>
                          <td colspan="5">
                            <a class="btn btn-warning float-right ml-2" href="/checkout/">Proceed to checkout</a>
                            <a class="btn btn-primary float-right" href="/">Continue shopping</a>
                          </td>
                        </tr>
                        
                      </tbody>
                    </table>
                  
                  </div>
            </div>
        </main>

        {% endblock %}

<!--        {% include 'footer.html' %}-->

        {% include 'script.html' %}

    </body>
</html>

templates/product-page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{object.item_image.url}}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="{{object.item_category.get_absolute_url}}">
                <span class="badge purple mr-1">{{object.item_category}}</span>
              </a>
<!--              <a href="">-->
<!--                <span class="badge red mr-1">{{object.get_labels_display}}</span>-->
<!--              </a>-->
              <span>
                {{object.item_name}}
              </span>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                  <del>{{object.price}}</del>
                </span>
              <span>{{object.discount_price}}</span>
              {% else %}
              <span>{{object.price}}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{object.description}}</p>

           <!--
             <form class="d-flex justify-content-left">
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form>
           --> <a href="{% url 'core:likes' slug=object.slug %}" class="btn btn-primary btn-md my-0 p">
                  <i class="fas fa-heart mr-1">  {{object.likes.count}}</i>
                </a>

           <a href="{{object.get_add_to_cart}}" class="btn btn-primary btn-md my-0 p">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
           </a>

           <a href="{{object.remove_from_the_cart}}" class="btn btn-danger btn-md my-0 p">Remove from the cart
            <i class="fas fa-shopping-cart ml-1"></i>
         </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>
        <div class="container">
            {% if comments.count != 0 %}
            <div class="row">
                <p>Total Comments {{comments.count}}</p>
            </div>
            {% endif %}
            <div class="row">
                <ul class="list-unstyled">
                    {% if comments %}
                    {% for comment in comments %}
                    <hr>
                    <li class="media">
                        <div class="media-body">
                            <h6 class="lead card-text"> Posted by: {{comment.user.username}}</h6>
                            <p class="lead card-text">{{comment}}</p>
                            <p class="lead card-text">Posted on: <strong>{{comment.date}}</strong></p>

                        </div>
                    </li>
                    {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
        {% if request.user.is_authenticated %}
        <h4 class="my-4">Leave a comment</h4>
      <form action="{% url 'core:comments' slug=object.slug %}" method="post">
           {% csrf_token %}
<!--            {{ form|crispy }}-->
          <div class="form-group">
              <textarea name="comment" cols="200" rows="3" class="form-control" placeholder="Write A Comment" required="" id="id_comment"></textarea>
          </div>
            <button type="submit" class="btn btn-primary">
              Post
          </button>
        </form>
        {% else %}
        <div class="row mt-1 mb-2">
            <a class="btn btn-danger text-black" type="button" href="/accounts/login/">Login to comment</a>
        </div>
        {% endif %}

      <!--Grid row-->
<!--      <div class="row d-flex justify-content-center wow fadeIn">-->

<!--        &lt;!&ndash;Grid column&ndash;&gt;-->
<!--        <div class="col-md-6 text-center">-->

<!--          <h4 class="my-4 h4">Additional information</h4>-->

<!--          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit-->
<!--            voluptates,-->
<!--            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>-->

<!--        </div>-->
<!--        &lt;!&ndash;Grid column&ndash;&gt;-->

<!--      </div>-->
      <!--Grid row-->

      <!--Grid row-->
<!--      <div class="row wow fadeIn">-->

<!--        &lt;!&ndash;Grid column&ndash;&gt;-->
<!--        <div class="col-lg-4 col-md-12 mb-4">-->

<!--          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">-->

<!--        </div>-->
<!--        &lt;!&ndash;Grid column&ndash;&gt;-->

<!--        &lt;!&ndash;Grid column&ndash;&gt;-->
<!--        <div class="col-lg-4 col-md-6 mb-4">-->

<!--          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">-->

<!--        </div>-->
<!--        &lt;!&ndash;Grid column&ndash;&gt;-->

<!--        &lt;!&ndash;Grid column&ndash;&gt;-->
<!--        <div class="col-lg-4 col-md-6 mb-4">-->

<!--          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">-->

<!--        </div>-->
<!--        &lt;!&ndash;Grid column&ndash;&gt;-->

<!--      </div>-->
      <!--Grid row-->

    </div>
  </main>

{% endblock %}